### ISSUE TITLE
were is apollo code

### ISSUE THREAD

**Issue by caspervanneck** [NycuRO/Apollo#1]

**Comment by NycuRO** [comment]
In 30mins i'm add all codes from genisys and start create all biomes :dancer: 

Now Apollo PHP7 :D

**Comment by NycuRO** [comment]
@caspervanneck please enter telegram group

**Comment by caspervanneck** [comment]
@NycuRO wath is your telegram group naam

**Comment by XtremePlayzCODE** [comment]
hey casper, your a member of xpocket now

**Comment by NycuRO** [comment]
@caspervanneck !
NO RECLAM

**Comment by NycuRO** [comment]
@XtremePlayzCODE .sorry casper

**Comment by caspervanneck** [comment]
@NycuRO what i make no raclam

**Comment by XtremePlayzCODE** [comment]
who deleted my thing?

**Comment by caspervanneck** [comment]
@XtremePlayzCODE im not

**Comment by XtremePlayzCODE** [comment]
?

**Comment by NycuRO** [comment]
@XtremePlayzCODE you can go to telegram group?

**Comment by XtremePlayzCODE** [comment]
wha?
