### ISSUE TITLE
hi how can y get a phar

### ISSUE THREAD

**Issue by lolcraftboy14** [NycuRO/Apollo#1]

**Comment by Aericio** [comment]
Compile it yourself, download the file from Github and put the [SRC] file in your server folder. Remove your other .phar's in the server folder (not plugins). Then do /makeserver and wait.

**Comment by NycuRO** [comment]
Or get feom CI-TRAVIS

**Comment by NycuRO** [comment]
From*

**Comment by NycuRO** [comment]
Sorry not*
