### ISSUE TITLE
spawn-protection doesnt work.

### ISSUE THREAD

**Issue by psycholyzern** [NycuRO/Apollo#21]
Before I started to describe, I would like you to know that I have this issue on Genisys, ClearSky, Nukkit, and yours.

spawn-protection seems doesnt work. I can destroy blocks even Im not an op. I dont know what is the caused of this issue because I simply cant enable spawn-protection on all MCPE server that I installed.
Im using debian 8 x64. Php was taken from Genisys'.

**Comment by Aericio** [comment]
I am not entirely sure that Genisys bins are the best.  If you are opting for a different option than Genisys, don't use their bins, use the normal Pocketmine-MP bins. I'll try to reproduce, but I have never used Apollo/Genisys so will take some time. Can you send me your server.properties?

**Comment by psycholyzern** [comment]
```                              
#Properties Config file
#Thu Aug 18 00:39:31 EDT 2016
server-name=Minecraft: PE Server                                                   motd=Minecraft: PE Server
server-port=19132
level-name=world
level-type=DEFAULT
gamemode=0
max-players=20
spawn-protection=30
announce-player-achievements=off
white-list=off
enable-query=on
enable-rcon=off
allow-flight=off
spawn-animals=on
spawn-mobs=on
force-gamemode=off
hardcore=off
pvp=on
difficulty=1
generator-settings=
level-seed=
rcon.password=S35HHQHQnI
auto-save=on
```

I will try to use Pocketmine-MP's bin. Btw, the weird thing is, I have this problem even on Nukkit, which is using java language.

Here the step I did to change the spawn-protection value.
1. Go to a new spot, and do /setworldspawn
2. Change spawn-protection to 30
3. Start Apollo.

Did I do it right? I also did that on Genisys, ClearSky and Nukkit. I have tried login with op and without op, both can destroy blocks around it.

**Comment by Aericio** [comment]
Can't reproduce right now, I don't know why my server won't let me connect even though I port forwarded.
@SalmonGER Help?

**Comment by psycholyzern** [comment]
I dont have any plugins, I just take phar, put bin, and start.
Btw I have tried uaing Pocketmine-MP's bin. Same issue still persist.

**Comment by Aericio** [comment]
Try making an issue to ClearSky or Genisys?

**Comment by psycholyzern** [comment]
I asked in telegram group of ClearSky, but they all dont know what is going on. 
I will try to make one at Genisys' later.

This seems pretty impossible to solve because it just me having this issue.

**Comment by Aericio** [comment]
Yeah, I am not having this problem. Also, try doing a clean reinstall of Pocketmine-MP?

**Comment by NycuRO** [comment]
@psycholyzern i know problem,need fixed :)

**Comment by NycuRO** [comment]
need test ,you can test @psycholyzern 

?

**Comment by psycholyzern** [comment]
Got this error, a lot of it.

 ```
[12:35:22] [Server thread/CRITICAL]: Could not tick level "world": Call to undefined method pocketmine\Player::getTransactionQueue()
```

**Comment by NycuRO** [comment]
please download latest version.
@psycholyzern

**Comment by psycholyzern** [comment]
Not working. I still can destroy block around spawn - http://i.imgur.com/rhw5BZoh.jpg
😞😞

**Comment by NycuRO** [comment]
for my work,idk why. Improve to more blocks . Put 200 blocks. and /setworldspawn again

**Comment by NycuRO** [comment]
@psycholyzern

**Comment by SalmonGER** [comment]
@Aericio You shouldn't tell a Apollo user or Genisys user to use normal PocketMine bins. Apollo is a fork of Genisys and Genisys has it's own bins and that has a reason. Genisys does not run with normal PocketMine bins.

**Comment by SalmonGER** [comment]
Can I try to join your server and break blocks? Also, did you change the spawn-protection value while the server is **completly shutdown**?

**Comment by psycholyzern** [comment]
I changed to 100 and it works. Seems that it has problems with small radius.
Sure you can join, 188.166.217.57 port 19132

If you want my ssh detail, I can give. Maybe you can find anything. It is a test server, so I dont mind.

**Comment by psycholyzern** [comment]
And, I changed the value while the server is running, and just do reload. I also tried while server is shutdown and rerun server after changed the value. Both still have same issue

**Comment by NycuRO** [comment]
very laggy server @psycholyzern

**Comment by SalmonGER** [comment]
@NycuRO Why that off-topic thing lol
@psycholyzern Does the value inside of the server.properties reset after you started the server? Can you look inside it again?

**Comment by psycholyzern** [comment]
Really @NycuRO ? It is located in singapore. Maybe the ping is high? Im using 512MB RAM server from digitalocean.com. and the Apollo servwr is the only thing I running right now.

**Comment by psycholyzern** [comment]
No @SalmonGER . it stay like what I already set.

**Comment by SalmonGER** [comment]
@psycholyzern Actually the server is running pretty well for me. What did you set as value? Where I stand right now I can't break blocks. I guess it works.

**Comment by psycholyzern** [comment]
I set to 100. Ok, right now I changed to 20.  Can you break now, or after relog?

**Comment by SalmonGER** [comment]
Spawn Protection works for me lol

**Comment by psycholyzern** [comment]
I set to 10 right now and reatarted the mcpe server. It is broken again.

**Comment by Aericio** [comment]
Disable Toolbox.

**Comment by caspervanneck** [comment]
disable toolbox for mcpe and it dont if you have op @psycholyzern

**Comment by caspervanneck** [comment]
.

**Comment by psycholyzern** [comment]
Like I said, I already tested with account with no op.
And I also already test with original mcpe client, I only use toolbox for fast mining.
Btw, it is okay, iasie seems impoasible to solve, so let it be.

**Comment by Aericio** [comment]
Just use AreaProtect or whatever

**Comment by caspervanneck** [comment]
Hmmm

**Comment by caspervanneck** [comment]
Shuld it be a bug from genisys maybe ??

**Comment by psycholyzern** [comment]
I dont know. Since that this issue is randomly happen to me, I just use what value that is working right now. I just need to avoid modifying the value, then Im ok. 
I guess this issue can be closed for now because I can live with how it is right now.
Thanks for all the friendly support :)
