### ISSUE TITLE
it dont start on windows

### ISSUE THREAD

**Issue by lolcraftboy** [NycuRO/Apollo#4]

**Comment by NycuRO** [comment]
you can give me error?

**Comment by NycuRO** [comment]
photo..?

**Comment by NycuRO** [comment]
photo..?

**Comment by lolcraftboy** [comment]
its fixt

**Comment by lolcraftboy** [comment]
it dont -_-
  can you help @NycuRO y get tish bin\php\php.exe: Exit 127

**Comment by NycuRO** [comment]
photo

**Comment by NycuRO** [comment]
or screenshot

**Comment by NycuRO** [comment]
no apollo problem . is php problem. apollo is php5

**Comment by lolcraftboy** [comment]
Y use php5 @NycuRO

**Comment by NycuRO** [comment]
@lolcraftboy hmm,your ram is ok?

**Comment by lolcraftboy** [comment]
Yes i tink

**Comment by NycuRO** [comment]
hmm,stay for create new commit

**Comment by NycuRO** [comment]
@lolcraftboy ready

**Comment by lolcraftboy** [comment]
@NycuRO y gone test

**Comment by NycuRO** [comment]
all works fine. tested

**Comment by Aericio** [comment]
bin\php\php.exe: Exit 127 = ram problem. Either lower the ram you give to the server or close all other pocketmine windows.
